- hosts: localhost
  gather_facts: no
  vars_files:
    - config.yml

  tasks:
  - name: ensure instances are running
    ec2:
      # Windows Server 2012R2
      # image: ami-281ad849
      # Windows Server 2012R2 Japanese
      image: ami-021de263
      instance_type: "{{ instance_type }}"
      key_name: "{{ key_name }}"
      group: "{{ group }}"
      region: "{{ region }}"
      wait: yes
      wait_timeout: 500
      exact_count: 1
      count_tag:
        Name: stock-win-ami-test
      instance_tags:
        Name: stock-win-ami-test
      user_data: "{{ lookup('template', 'userdata.j2') }}"
    register: ec2_result

  - name: wait for WinRM to answer on all hosts
    wait_for:
      port: 5986
      host: "{{ item.public_ip }}"
      timeout: 300
    with_items: ec2_result.tagged_instances

  - name: add hosts to groups
    add_host:
      name: "windows-host"
      ansible_ssh_host: "{{ item.public_ip }}"
      groups: win
    changed_when: false
    with_items: ec2_result.tagged_instances

- hosts: win
  gather_facts: no
  vars_files:
    - config.yml
  tasks:
    - include: tasks.yml
