admin_password: ADMIN_PASSWORD
user_name: USER_NAME
user_password: USER_PASSWORD

# Windows Server 2012R2
# image: ami-281ad849
# Windows Server 2012R2 Japanese
# image: ami-021de263
image: IMAGE

# instance_type: t2.large
instance_type: INSTANCE_TYPE

# group: default
group: GROUP

# region: ap-northeast-1
region: REGION

key_name: KEY_NAME
